# Generated by Django 5.2.4 on 2025-07-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('roldescription', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
                ('course', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=45)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_approved', to='violations.userdetails')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations_reported', to='violations.userdetails')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='imageID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('violation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='violations.violation')),
            ],
        ),
    ]
