# Generated by Django 5.2.4 on 2025-07-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roldescription',
            new_name='roledescription',
        ),
    ]
