# Generated by Django 5.2.4 on 2025-07-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_rename_roldescription_role_roledescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageID',
            new_name='Image',
        ),
    ]
