# Generated by Django 4.2 on 2025-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_alter_image_id_alter_role_id_alter_studentinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_violations', models.PositiveIntegerField(default=0)),
                ('active_cases', models.PositiveIntegerField(default=0)),
                ('student_involved', models.PositiveIntegerField(default=0)),
                ('resolved', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
