# Generated by Django 4.2 on 2025-08-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('violations', '0005_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guard', 'Guard'), ('council', 'Council')], max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='active_cases',
            new_name='pending',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='resolved',
            new_name='scheduled',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='student_involved',
            new_name='total_cases',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='total_violations',
            new_name='under_review',
        ),
        migrations.RenameField(
            model_name='violation',
            old_name='student_id',
            new_name='student_name',
        ),
        migrations.CreateModel(
            name='ViolationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=500)),
                ('date_reported', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.user')),
            ],
        ),
    ]
