# Generated by Django 4.2 on 2025-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_usermanagement_rename_active_cases_dashboard_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reported_by', models.CharField(max_length=100)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('scheduled', 'Scheduled'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
            ],
        ),
    ]
