# Generated by Django 4.2 on 2025-08-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0008_student_scanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reported_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.student')),
            ],
        ),
    ]
